### ISSUE TITLE
Transparencies are lost when resizing or rotating gif images

### ISSUE THREAD

**Issue by elboletaire** [elboletaire/Watimage#25]

**Comment by ldbglobe** [comment]
I hope this help you to handle GIF transparency
https://gist.github.com/miguelxt/908143#gistcomment-1488540

I use a similar method to fix GIF transparency support on my own image library

**Comment by elboletaire** [comment]
Yay! I'll take a look into it whenever I can. I hope it serves me!

Thanks :smile:

**Comment by elboletaire** [comment]
Fixed for resizing. The rotate issue seems to be a bug in `rotate`. I need to check it further.

I've created #31 to fix that apart, as it's a different issue.
