### ISSUE TITLE
want to use this class without autoload.php

### ISSUE THREAD

**Issue by circuitmamu** [elboletaire/Watimage#30]
i want to use this class without autload.php and also without namespace.

I tried removing it and want to use directly include the files that is necessary but it's doesn't seems to be run and stuck in loop of codes

**Comment by elboletaire** [comment]
Please, paste me here what you tried because I've been able to do this just requiring all the files one by one.

**Comment by circuitmamu** [comment]
can you give me in which sequence you require the files beacuse use and namesapce will give me error.

I want to use this class make watermarked image with it;s thumb of 240 x 240 in same code when any file is uploaded.

**Comment by elboletaire** [comment]
Just require all the required files one by one.. I don't get what's your problem and you don't help not being specific (plus not answering what I'm asking..).

**Comment by circuitmamu** [comment]
@elboletaire can you please give me in which sequence you require the files
I'm try to require the files one by one but still getting error or namespaces

**Comment by elboletaire** [comment]
There's no specific sequence, simply require all the files needed:

```php
use Elboletaire\Watimage\Image;

define('DS', DIRECTORY_SEPARATOR);
define('PATH', dirname(__FILE__) . DS);
define('WATIMAGE', PATH . 'Watimage' . DS . 'src' . DS);

require WATIMAGE . 'Image.php';
require WATIMAGE . 'Watermark.php';

$image = new Image('test.jpg');
// [...]
```
