### ISSUE TITLE
Using a png file to watermark a gif image.

### ISSUE THREAD

**Issue by daniel-nemeth** [elboletaire/Watimage#6]
If i try to watermark an gif image with a png watermark file, the gif is transparent, but the png watermark has a black background.

![screen shot 2014-11-21 at 21 16 25](https://cloud.githubusercontent.com/assets/5083254/5148882/ac44fcd8-71c3-11e4-92fa-237046fe3c30.png)

**Comment by daniel-nemeth** [comment]
Yes, this is right. Both should be transparent after the watermark.

**Comment by elboletaire** [comment]
I'll try to fix it then.

**Comment by elboletaire** [comment]
It seems that when I made Watimage I didn't expected gif images to be used as watermarks, instead, the code is built just for using png images as watermark.

I'll try to work on it during these days. Theoretically the `imagecopyresampled` used in the internal method `resize_png_image` (which will be renamed, as it names clearly states that it's just for png images) does not maintain the alpha for gif images. Instead I'll need to use `imagecopyresized` method.

[This stackoverflow answer](http://stackoverflow.com/a/4693473/407456) saved me a lot of time. :smile: Now I expect the theory to be possible... :sweat_smile:

**Comment by elboletaire** [comment]
HHhmmm... after testing it by myself I can only see the script failing when using gif images as background (if those images have alpha they loose it) but watermarking gif files with png does not negatively affect the watermark.

Are you sure that the image that gains a black background is the png image? Isn't it the gif image used as backgruond?

Here are my tests using gif images as background...

### Gif with gif
![gif with gif](https://cloud.githubusercontent.com/assets/153305/8384957/fb2a44e4-1c44-11e5-94fb-3d15d7f39c16.png)
### Gif with png
![gif with png](https://cloud.githubusercontent.com/assets/153305/8384965/0f9b44fa-1c45-11e5-99e9-2307bccd0c2e.png)

As you can see, the watermark image doesn't loose it's transparency, whilst the gif image used as background does.

I've also tested any other circumstance (using always gif or png files for watermarks) and there are no more failures, so I'll try to fix this issues.
